Bug fix: Fixes bug in readme contributor badge
KalleHallden/exer_log pull request #107
Opened 2022-08-20 16:32 UTC by abhpd

<img width="919" alt="image" src="https://user-images.githubusercontent.com/34980034/185756970-0a60db01-ad9f-4ce5-8c6e-240402aec8fc.png">
<img width="924" alt="image" src="https://user-images.githubusercontent.com/34980034/185757054-87ec5f68-455c-4966-8647-97d1bc61e706.png">

2022-08-20 20:29 UTC, 0RaMsY0 commented
can you change the 
``` 
(#contributors-)
```
into 
``` 
(#contributors)
```
because if you click that badge it will not scroll the contributors section while there is that ```-``` in there.

2022-08-20 21:07 UTC, PickleNik requested changes
<img width="948" alt="Screen Shot 2022-08-20 at 5 05 41 PM" src="https://user-images.githubusercontent.com/31113245/185766005-383cb73d-fb31-45d0-bf2b-d6c581389086.png">
This doesn't look like the screenshot you've sent.
Please take a look at #119 for centering the link and change the link as suggested above.
Thank you :)

2022-08-20 21:07 UTC, PickleNik commented on README.md
>  [![All Contributors](https://img.shields.io/badge/all_contributors-6-orange.svg?style=flat-square)](#contributors-)
needs `#contributors` instead of `#contributors-`, otherwise the link doesn't work

2022-08-21 09:09 UTC, abhpd commented
> <img alt="Screen Shot 2022-08-20 at 5 05 41 PM" width="948" src="https://user-images.githubusercontent.com/31113245/185766005-383cb73d-fb31-45d0-bf2b-d6c581389086.png">
> 
> This doesn't look like the screenshot you've sent.
> Please take a look at #119 for centering the badge and change the link as suggested above. Thank you :)

I think there is some issue with the github preview. You can check my fork here: https://github.com/abhpd/exer_log/tree/readme-contributor-badge-fix

2022-08-21 09:10 UTC, abhpd commented
I think #119 is also a valid solution. If we're satisfied with it we can close this PR.

2022-08-21 16:21 UTC, PickleNik commented
> @PickleNik I think there is some issue with the github preview. You can check my fork here: https://github.com/abhpd/exer_log/tree/readme-contributor-badge-fix

You're right, the preview is weird.

2022-08-21 16:26 UTC, PickleNik commented
> I think #119 is also a valid solution. If we're satisfied with it we can close this PR.

Your solution is more slim, I like it, however the [bot rc badgeTemplate](https://github.com/KalleHallden/exer_log/blob/alpha/.all-contributorsrc#L65) needs to be changed to match. (every time Kalle uses the bot to add contributors to the readme, the bot modifies the section between the `<!-- ALL-CONTRIBUTORS-BADGE:START -->` and `<!-- ALL-CONTRIBUTORS-BADGE:END-->` comments with the badgeTemplate).

2022-08-21 16:45 UTC, PickleNik commented
@abhpd, there is 3 PRs for this little readme bug 😅, I think #129 covers it best, thanks for all the effort, but I think it's best to close this in favor of #129 to reduce the load on Kalle in checking all of them :)

2022-08-22 06:20 UTC, abhpd commented
@PickleNik Sure thanks 🙌

2022-08-22 06:20 UTC, closed without merging