Feat: remove ThemeProvider and use theme in MaterialApp
KalleHallden/exer_log pull request #153
Opened 2022-08-25 15:55 UTC by hoffmannkrzysztof

2022-08-25 16:09 UTC, dinurymomshad commented
@hoffmannkrzysztof please update your branch with the latest changes from alpha. Resolve the conflicts.

2022-08-25 16:13 UTC, jorre127 commented
@hoffmannkrzysztof  Thanks for helping out. But there was a reason we were using the themeProvider haha. So you shouldn't remove all the theme providers. using the build in material theme certainly isn't a bad idea though as it gives a lot of ui items a standard color so you don't have to define it every time so you can definitely keep that. But when defining a custom color for a ui item it's better to use the custom implementation we currently have because it gives us way more freedom because it allows us to make our own ui tokens. Also the current implementation currently makes it easy to have multiple themes like dark mode, light mode, custom etc. Also i was planning to store the textThemes in the AppTheme as well so they also support multiple themes. So could you maybe undo all the places where you removed the theme provider, but keep the materialTheme you added? This will also help with the merge conflicts.

2022-08-25 16:26 UTC, hoffmannkrzysztof commented
Sure no problem at all. I leave it only changes in MaterialApp

2022-08-25 16:35 UTC, jorre127 commented
Thanks, sorry after you went trough the trouble.

2022-08-25 18:15 UTC, jorre127 approved these changes

2022-08-26 06:37 UTC, jorre127 commented on lib/UI/workout/workout_page_widgets.dart
> +      {Key? key, required this.firstLoad, required this.workoutData})
put a comma at the end and format

2022-08-26 06:37 UTC, jorre127 commented on lib/UI/workout/workout_page_widgets.dart
> +          FocusScope.of(context).requestFocus(new FocusNode());
use arrow function here

2022-08-26 06:37 UTC, jorre127 commented on lib/UI/workout/workout_page_widgets.dart
> +    });
add comma

2022-08-26 06:37 UTC, jorre127 commented on lib/UI/workout/workout_page_widgets.dart
> +                        totals: workoutData.totals,
Personally when a widget only Hase 1 parameter I just put it on 1 line

2022-08-26 06:37 UTC, jorre127 commented on lib/UI/workout/workout_page_widgets.dart
> +                color: theme.colorTheme.backgroundColorVariation,
same here

2022-08-26 06:39 UTC, hoffmannkrzysztof commented
Wrong branch :)

2022-08-26 16:51 UTC, dinurymomshad commented
> Wrong branch :)

What is the update of this?

2022-08-26 17:07 UTC, hoffmannkrzysztof commented
I have already reverted unnecessary commit. So only changes to MaterialApp are included in this PR.

2022-08-26 17:32 UTC, tenshiAMD requested changes
@hoffmannkrzysztof please rebase and add a brief description in this PR. Thanks!

2022-09-02 17:41 UTC, tenshiAMD approved these changes

2022-09-02 17:42 UTC, tenshiAMD requested changes
@hoffmannkrzysztof LGTM however please add a brief description about your changes first before we can merge this one. Thanks!

2022-09-03 00:02 UTC, tenshiAMD approved these changes

2022-09-03 00:04 UTC, tenshiAMD commented
@hoffmannkrzysztof LGTM, thanks! 

@dinurymomshad @jorre127 I will leave the merging for you guys

2022-09-16 15:58 UTC, tenshiAMD commented
> @dinurymomshad @jorre127 I will leave the merging for you guys

@dinurymomshad @jorre127 gentle ping

2022-09-16 20:10 UTC, merged