refactor: always_specify_types linter rule
KalleHallden/exer_log pull request #201
Opened 2022-09-28 17:49 UTC by mfederowicz

### Summary

refactor code to pass following linter rules:

- always_specify_types

2022-09-28 17:55 UTC, tenshiAMD approved these changes

2022-09-28 18:06 UTC, mfederowicz commented
@tenshiAMD of course there are some difficult case where I dont know how to specify type, for example:

```
validator: (value) => Validators.requiredField(value),
```

```
final FutureOr Function() onPressed;
```

```
Navigator.of(context).push(
      MaterialPageRoute(
        builder: (BuildContext context) => WorkoutPage(null),
      ),
    );

```

or

```
return defaultValue ?? {};
```

but i dont want to add everywhere :  

```
// ignore: always_specify_types
```
because it is not ok and clean solution :(

2022-09-28 18:51 UTC, tenshiAMD requested changes
@mfederowicz Let's wait for @jorre127 to review this one.

2022-09-30 19:33 UTC, jorre127 commented
@mfederowicz For this one: 

`validator: (value) => Validators.requiredField(value),`

you can just turn it into this: 

`validator: (String? value) => Validators.requiredField(value),`

And then also change the validator in the textField from ` final FormFieldValidator validator;` to   `final FormFieldValidator<String> validator;`

Pretty sure the `final FutureOr Function() onPressed;` can be changed to `final Future<void> Function() onPressed;` seeing as an on pressed shouldn't really return anything, and don't think it does here.

For the navigation we can just specify void as return type. Unless we await the navigation and expect a value to be returned. But most times we don't await so we can just do it like this: 

```
      MaterialPageRoute<void>(
        builder: (BuildContext context) => WorkoutPage(null),
      ),
```

And lastly you can turn into `return defaultValue ?? {};` ` return defaultValue ?? <String, dynamic>{};` to specify the type of a map.

Can you maybe make these fixes? Then I'll check the PR cause it doesn't seem like all the specify type warnings have been fixed.

2022-09-30 20:55 UTC, mfederowicz commented
Ok @jorre127 i fixed code in places you provided, for now there 34 places to potential fix(improvement) :)

2022-10-01 07:57 UTC, jorre127 commented on lib/src/feature/calendar/widgets/calendar_widget.dart
> +    // ignore: always_specify_types
Remove this comment

2022-10-01 07:57 UTC, jorre127 commented on lib/src/feature/calendar/widgets/logout_button.dart
> +// ignore: always_specify_types
Also remove this one and specify the types in this file

2022-10-01 07:57 UTC, jorre127 commented on lib/src/feature/onboarding/splash/view/splash_screen.dart
> +      // ignore: always_specify_types
Do a search in vscode (or whatever editor you're using) and remove all instances of `// ignore: always_specify_types `then you can easily see what files you have missed.

2022-10-01 07:57 UTC, jorre127 commented on lib/src/feature/authentication/view/landing_screen.dart
> +    ref.listen(AuthenticationController.provider, (_, Object? state) {
Try to be as specific as possible with your types, you should almost never use Object. In this case for example pretty sure this provides a BaseState so change the code to:

` ref.listen<BaseState>(AuthenticationController.provider, (_, BaseState? state) {`

2022-10-01 07:59 UTC, jorre127 commented
@mfederowicz It's looking good, I think we're almost done. Only it doesn't seem that all the warnings are fixed yet, can you fix these ones? And the ones that pop back up when you delete all the // ignore comments. Feel free to send a message here if you don't know how to specify a type for a specific line

2022-10-01 12:27 UTC, mfederowicz commented
@jorre127 almost there, some problematic cases:

```
class _LogoutButtonState extends State<LogoutButton> with Dialogs {
```

```
body: firstLoad
              ? FutureBuilder(
```

```
Expanded(
                flex: 10,
                child: ValueListenableBuilder(
```

```
_notifier = ValueNotifier(widget.totalsWidget.totals);
```

```
Container(
                            child: ValueListenableBuilder(
                              valueListenable: _notifier,
```

2022-10-01 12:46 UTC, jorre127 commented
@mfederowicz You can change them to:
```
class _LogoutButtonState extends State<LogoutButton> with Dialogs<LogoutButton>
```
```
body: firstLoad
    ? FutureBuilder<List<Workout>>(
```
I used SetData here but you basically just have to match the type here to the type that is passed to the valueListenable property of this widget.
```
Expanded(
  flex: 10,
  child: ValueListenableBuilder<SetData>(
    valueListenable: _notifier,
```
```
_notifier = ValueNotifier<TotalsData>(widget.totalsWidget.totals);
```
and
```
child: ValueListenableBuilder<TotalsData>(
```

2022-10-01 12:47 UTC, jorre127 commented
@mfederowicz  Can you also maybe from now on put all your changes in seperate commits, because now it's hard to see what are new changes and which ones were already checked.

2022-10-01 12:59 UTC, mfederowicz commented
@jorre127 no problemo :P

2022-10-01 13:17 UTC, jorre127 approved these changes

2022-10-01 13:29 UTC, mfederowicz commented
ok @tenshiAMD i squashed commits and PR is ready to merge to alpha :)

2022-10-03 14:35 UTC, merged