proposal for linter analysis options
KalleHallden/exer_log pull request #58
Opened 2022-08-13 11:53 UTC by BertVanMieghem

An initial proposal for some linter rules. These are the ones I use personally, they are not very strict but might be a good start.
Check out https://dart.dev/tools/linter-rules

2022-08-13 12:24 UTC, jorre127 commented on app/exerlog/analysis_options.yaml
> +    always_put_required_named_parameters_first: false
I would put this one on as well.

2022-08-23 07:27 UTC, jorre127 commented
@BertVanMieghem Is this still being worked on ?

2022-08-24 22:18 UTC, tenshiAMD requested changes
@BertVanMieghem Hi, please rebase to alpha branch then fix conflicts. Thanks!

2022-09-12 12:21 UTC, mfederowicz commented
@BertVanMieghem Hi, what is the status of this PR, maybe some help needed?

2022-09-12 17:21 UTC, tenshiAMD commented
> @BertVanMieghem Hi, what is the status of this PR, maybe some help needed?

@mfederowicz sure you can help here

2022-09-12 21:14 UTC, mfederowicz commented
Ok @tenshiAMD but what is the plan, I have https://github.com/mfederowicz/exer_log/tree/lintr - cleanedup, 1 ahead to alpha, so should I create another PR?

2022-09-12 21:26 UTC, tenshiAMD commented
> Ok @tenshiAMD but what is the plan, I have [https://github.com/mfederowicz/exer_log/tree/lintr](https://github.com/mfederowicz/exer_log/tree/lintr?rgh-link-date=2022-09-12T21%3A14%3A56Z) - cleanedup, 1 ahead to alpha, so should I create another PR?

@mfederowicz yes then we close and reference this PR to the new PR. Thanks.

2022-09-12 21:47 UTC, mfederowicz commented
@tenshiAMD ok but can you lookup on content of pubspec.lock, because iam affraid of update some parts, especially material_color_utilities or flutter_riverpod those packages bump up version after:

```
flutter pub get
```

2022-09-15 01:16 UTC, mfederowicz commented
ok @tenshiAMD problem with pubspec.loc solved, i pushed changes related only with linter, we can close this PR and focus on: https://github.com/EXERLOG/exer_log/pull/191

2022-09-16 15:42 UTC, tenshiAMD commented
> ok @tenshiAMD problem with pubspec.loc solved, i pushed changes related only with linter, we can close this PR and focus on: #191

@mfederowicz ok thanks

@BertVanMieghem we are closing this one for now. thanks.

2022-09-16 15:42 UTC, closed without merging